name: Tests

on:
    push:
    pull_request:

jobs:
    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest

        env:
            XDEBUG_MODE: coverage

        strategy:
            matrix:
                php: [ '8.2', '8.3', '8.4', '8.5' ]

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 10

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
                    coverage: xdebug

            -   name: Setup Problem Matchers
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -   name: Install PHP Dependencies
                uses: nick-fields/retry@v3
                with:
                    timeout_minutes: 5
                    max_attempts: 5
                    command: composer update --no-interaction --no-progress

            -   name: Execute PHPcs
                run: vendor/bin/phpcs --standard=PSR2 src/ tests/

            -   name: Execute PHPUnit
                run: vendor/bin/phpunit --coverage-clover=coverage.xml
            -   name: Upload coverage to Codecov
                if: matrix.php == '8.4'
                uses: codecov/codecov-action@v5
                with:
                    files: ./coverage.xml
                    flags: unittests
                    name: codecov-umbrella
                    token: ${{ secrets.CODECOV_TOKEN }}
                    fail_ci_if_error: true
